const express = require("express");
const app = express();
var http = require('http');
const server = http.createServer(app);
const router = express.Router();
var date = new Date();
const path = require('path');
let bodyParser = require("body-parser");
const chalk = require('chalk');
app.use('/', router);
server.listen(3001);
console.log(chalk.bold.cyan('--------- Denote --------- '));
console.log(chalk.bold.cyan(` Created by Francis Borja `));
console.log(chalk.gray(`Server running at port 3001`));
console.log(chalk.gray('---------------------------'));
